apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: catalog-route
  namespace: moto-catalog
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`dashboard.moto-lab.local`) && PathPrefix(`/catalog`)
      kind: Rule
      services:
        - name: catalog-service
          port: 80
      middlewares:
        - name: catalog-strip-prefix
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: catalog-strip-prefix
  namespace: moto-catalog
spec:
  stripPrefix:
    prefixes:
      - /catalog
