apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-advisor-sa
  namespace: platform-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcp-advisor-cluster-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"] # <- Solo lectura de nodos, Jarvis no puede romper nada
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-advisor-role-binding
subjects:
  - kind: ServiceAccount
    name: mcp-advisor-sa
    namespace: platform-tools
roleRef:
  kind: ClusterRole
  name: mcp-advisor-cluster-role
  apiGroup: rbac.authorization.k8s.io
