apiVersion: v1
kind: Service
metadata:
  name: envoy-kind-bridge-svc
  namespace: envoy-gateway-system
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080 # El contenedor de Envoy internamente suele escuchar en el 8080
      nodePort: 80     # Alínea con el extraPortMapping de Kind
  selector:
    gateway.envoyproxy.io/gateway-name: moto-lab-gateway
